
apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  labels:
    app: hellowprld
spec:
  selector:
    app: hello-world
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      